### ISSUE TITLE
How to prepare the input data

### ISSUE THREAD

**Issue by ysbioinfo** [smshuai/DriverPower#11]
Hi
I want to use DriverPower for my WGS data on gastric cancer. I have read the quick start guide but I think the data format is too difficult for me, possibly also for other users to produce. Most of us only have a list of coordinates for mutations, or a list of annotated mutations. To transform them to the data format required by DriverPower will takes a lot of time. 
Could you be so kind to provide some scripts to help us prepare the input files? (e.g. Only a list of mutations are needed). If so, I will be so grateful and I think there will be more users of DriverPower.
Thanks.

Yours 
Yang

**Comment by smshuai** [comment]
@snoopy-448 Hi Yang, thanks for your post. I realized that data preparation may be hard for some users, especially the preparation of genomic features. I'm thinking about host some reference data for hg19. Could you let me know what types of element sets you are interested in? I can provide data for standard sets like CDS, UTRs, promoter, ncRNA and enhancer. Are these sets sufficient?

**Comment by ysbioinfo** [comment]
Hi Shuai,
Thanks for your reply!
That would we great! I think these elements are enough for most users. By the way, it will be more convenient if you could provide the length of each element required by the response table.
I have two more questions:
1. I have a list of mutations, and annotate them by some widely used annotators. (like ANNOVAR, Oncotator...). These annotators will tell me whether a mutation is on the CDS, intron, or UTR of a gene, but could not tell me which enhancer/promoter this mutation belongs to. So I don't know how to prepare the response table for promoter and enhancer. Do other annotators have this function? Could you give me some advice?
2. In my opinion(I'm not sure whether I understand it correctly), response table and feature table are only  responsible for the mutation burden, if I want to consider the impact of mutations, I must include the functional score table. Which annotator can provides me the functional score(like CADD) of each mutation, and if there are more than one mutations on an element(like TP53.cds) and each has a CADD score, how to calculate the final CADD score?
Thank you very much!

**Comment by mksamur** [comment]
Hi Shuai
Do you have any update on input file preparation?

**Comment by smshuai** [comment]
Hi,
Sorry for the delay, I was busy with another project. I have prepared a [tutorial](https://driverpower.readthedocs.org/en/latest/tutorial.html) with some example data. The minimal requirement to run your own data will be a list of somatic mutations.
