### ISSUE TITLE
infer problem

### ISSUE THREAD

**Issue by ningwei-wei** [smshuai/DriverPower#17]
Hi,
i have some problem with the commod "infer".
frist question ,when i run it, there has some warings,like:
```
[10:34:27] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost_1598185621802/work/src/learner.cc:516: 
Parameters: { early_stopping_rounds, num_boost_round, silent, verbose_eval } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.
```
second question ,when i run your example data, it's result is some strange. i can't find angthings if i set the threshold q <0,1.so this is normal?

I hope to receive your reply as soon as possible. Thank you very much for that

**Comment by smshuai** [comment]
Hi ningwei,

The example data used randomized mutations, so it's normal and you should not find q<0.1 elements with the example data. 

Regarding the xgboost warning, I would suggest you run with your data first and see what's in the results.

**Comment by ningwei-wei** [comment]
Hi smshuai,
First of all, thank you for your quick reply. 
i had run my data ,but the result still strange. this is my result
|  tumor type   | sample number  | mutation number | candidate elements(q<0.1) |
|  ----  | ----  | ---- | ---- |
| CLL  | 32 | 2159725 | 1 |
| CRC  | 30 | 521271 | 15858 |
| NSCL | 30 | 1717259 | 9 |

This is how it works
```shell
01/03/2021 11:39:16 | INFO: Whitelisted elements: 1458292412/1471340700 bp (99.11%)
01/03/2021 11:40:04 | INFO: Whitelisted elements: 110797964/113350236 bp (97.75%)
01/03/2021 11:40:12 | INFO: Welcome to DriverPower v1.0.2
01/03/2021 11:41:42 | INFO: Successfully load 1373 features for 867266 bins
01/03/2021 11:41:48 | INFO: Use 867266 bins in model training
01/03/2021 11:41:53 | INFO: Split data fold 1/3
01/03/2021 11:42:01 | INFO: Split data fold 2/3
01/03/2021 11:42:09 | INFO: Split data fold 3/3
01/03/2021 11:42:16 | INFO: Training GBM fold 1/3
[11:42:16] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost_1598185621802/work/src/learner.cc:516:
Parameters: { early_stopping_rounds, num_boost_round, silent, verbose_eval } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[0]     eval-poisson-nloglik:71538.43750
Will train until eval-poisson-nloglik hasn't improved in 5 rounds.
[100]   eval-poisson-nloglik:15856.41309
[200]   eval-poisson-nloglik:3508.50635
[300]   eval-poisson-nloglik:771.82904
[400]   eval-poisson-nloglik:166.95296
[500]   eval-poisson-nloglik:34.87793
[600]   eval-poisson-nloglik:7.46253
[700]   eval-poisson-nloglik:2.69319
[800]   eval-poisson-nloglik:2.14314
[900]   eval-poisson-nloglik:2.10821
Stopping. Best iteration:
[916]   eval-poisson-nloglik:2.10777

01/03/2021 12:47:31 | INFO: Training GBM fold 2/3
[12:47:31] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost_1598185621802/work/src/learner.cc:516:
Parameters: { early_stopping_rounds, num_boost_round, silent, verbose_eval } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[0]     eval-poisson-nloglik:71228.46875
Will train until eval-poisson-nloglik hasn't improved in 5 rounds.
[100]   eval-poisson-nloglik:15787.38477
[200]   eval-poisson-nloglik:3492.94800
[300]   eval-poisson-nloglik:768.20911
[400]   eval-poisson-nloglik:166.05115
[500]   eval-poisson-nloglik:34.63113
[600]   eval-poisson-nloglik:7.40739
[700]   eval-poisson-nloglik:2.70300
[800]   eval-poisson-nloglik:2.16468
[900]   eval-poisson-nloglik:2.12741
Stopping. Best iteration:
[925]   eval-poisson-nloglik:2.12675

01/03/2021 13:50:11 | INFO: Training GBM fold 3/3
[13:50:11] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost_1598185621802/work/src/learner.cc:516:
Parameters: { early_stopping_rounds, num_boost_round, silent, verbose_eval } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[0]     eval-poisson-nloglik:70901.72656
Will train until eval-poisson-nloglik hasn't improved in 5 rounds.
[100]   eval-poisson-nloglik:15715.28613
[200]   eval-poisson-nloglik:3477.26978
[300]   eval-poisson-nloglik:764.98053
[400]   eval-poisson-nloglik:165.56874
[500]   eval-poisson-nloglik:34.70294
[600]   eval-poisson-nloglik:7.52934
[700]   eval-poisson-nloglik:2.76730
[800]   eval-poisson-nloglik:2.17172
[900]   eval-poisson-nloglik:2.11628
Stopping. Best iteration:
[978]   eval-poisson-nloglik:2.10977

01/03/2021 14:59:27 | INFO: Model metrics for training set: r2=0.25, Variance explained=0.25, Pearson'r=0.50
01/03/2021 14:59:35 | INFO: Job done!
01/03/2021 14:59:56 | INFO: Welcome to DriverPower v1.0.2
01/03/2021 14:59:56 | INFO: Model type: GBM
01/03/2021 14:59:56 | INFO: Results will be saved to /slst/home/ningwei/mutation/CLL/new-output with prefix DriverPower_burden
01/03/2021 15:00:10 | INFO: Successfully load 1373 features for 139404 bins
[15:00:17] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost_1598185621802/work/src/learner.cc:516:
Parameters: { early_stopping_rounds, num_boost_round, silent, verbose_eval } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[15:00:18] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost_1598185621802/work/src/learner.cc:516:
Parameters: { early_stopping_rounds, num_boost_round, silent, verbose_eval } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[15:00:19] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost_1598185621802/work/src/learner.cc:516:
Parameters: { early_stopping_rounds, num_boost_round, silent, verbose_eval } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


01/03/2021 15:00:20 | INFO: Model metrics for training set: r2=-0.34, Variance explained=-0.31, Pearson'r=0.38
01/03/2021 15:00:20 | INFO: Using negative binomial test with s=1, theta=1.0061479560513789
01/03/2021 15:00:27 | INFO: Job done!
```

i don't know where is wrong, can i share some data for you? so you can help me find  the problem.

CLL mutation [data](https://ningwei-1304664932.cos.ap-shanghai.myqcloud.com/cll-WGS-mutation.tsv.gz)
CRC mutation[data](https://ningwei-1304664932.cos.ap-shanghai.myqcloud.com/crc-WGS-mutation.tsv.gz)
NSCL mutation[data](https://ningwei-1304664932.cos.ap-shanghai.myqcloud.com/nscl-WGS-mutation.tsv.gz)

**Comment by smshuai** [comment]
Hi Ningwei,

It seems that CLL and NSCL are giving you correct number of hits given the number of samples you have. You could further quality check this with pvalue Q-Q plot, such as [here](https://rdrr.io/bioc/GWASTools/man/qqPlot.html).

Based on the number of mutations in CRC, I'm wondering are those WGS or WES data? It's strange to me that the CRC cohort has only 500K mutations while CLL and NSCL have 2M mutations.

**Comment by ningwei-wei** [comment]
Hi smshuai,

i check my CRC data carefully, i think it is WGS data undoubtedly. this is my download data.
[icgc data](https://dcc.icgc.org/search?filters=%7B%22donor%22:%7B%22projectId%22:%7B%22is%22:%5B%22COCA-CN%22%5D%7D,%22availableDataTypes%22:%7B%22is%22:%5B%22ssm%22%5D%7D,%22analysisTypes%22:%7B%22is%22:%5B%22WGS%22%5D%7D%7D%7D&donors=%7B%22from%22:1%7D)

i also plot pvalue Q-Q plot for CLL and NSCL 

![CLL-plot](https://user-images.githubusercontent.com/71494593/103540171-46099b00-4ed4-11eb-931a-f850df77360e.png)
![NSCL-plot](https://user-images.githubusercontent.com/71494593/103540175-4a35b880-4ed4-11eb-9183-7c2fba827edc.png)

Does this mean that the model is unreasonable ？

**Comment by smshuai** [comment]
Thanks for sharing the plots. Could you also look into or share the response and result tables? You have a lot of p-value=1 elements. This is usually caused by the number of mutations per element = 0 or 1.

**Comment by ningwei-wei** [comment]
Hi smshuai,

yes, my response table has  many elements' mutation =0 or 1. Should I delete them in the follow-up study?  Does it affect modeling？

yesterday, i delated hypomuation sample on my data and run again .the result is still strange
|  tumor type   | sample number  | mutation number | candidate elements(q<0.1) |
|  ----  | ----  | ---- | ---- |
| CLL  | 29 | 232681 | 9 |
| CRC  | 30 | 521271 | 15858 |
| NSCL | 27 | 1144629 | 7 |

CRC data doesn't have hypomutation sample, so it's result no change .

this is the CLL's response and result table

[train_y.tsv](https://ningwei-1304664932.cos.ap-shanghai.myqcloud.com/mutation/train_y.tsv)
[test_y.tsv](https://ningwei-1304664932.cos.ap-shanghai.myqcloud.com/mutation/test_y.tsv)
[result.tsv](https://ningwei-1304664932.cos.ap-shanghai.myqcloud.com/mutation/DriverPower_burden.result.tsv)

this is the CRC's response and result table

[train_y.tsv](https://ningwei-1304664932.cos.ap-shanghai.myqcloud.com/mutation/crc-train_y.tsv)
[test_y.tsv](https://ningwei-1304664932.cos.ap-shanghai.myqcloud.com/mutation/crc-test_y.tsv)
[result.tsv](https://ningwei-1304664932.cos.ap-shanghai.myqcloud.com/mutation/crc-DriverPower_burden.result.tsv)

it is strange that the CLL data is samilary with CRC data, but thsis result has more different

**Comment by smshuai** [comment]
Hi Ningwei,

Thanks for sharing the result. In your case, 80-90% train or test elements have no mutation, which means when you build a model based on this, the predicted # of mutations are very likely to be 0 as well. Thus, elements with a few mutations may become significant (very small p-value), which will cause a high false positive rate as in CRC.

I think what you could try is to remove those with 0 mutations and re-run again for CRC, but the best way is to collect more samples and get more mutations.

**Comment by ningwei-wei** [comment]
OK， Thank you for your patience and helpful reply.

i will try again when i collect more samples.

Good luck!!
